/Users/chenshuai/Documents/Project/easymoney/QUANTAXIS/task.sh: line 5: python3: command not found
/Users/chenshuai/Documents/Project/easymoney/QUANTAXIS/task.sh: line 5: python3: command not found
/Users/chenshuai/Documents/Project/easymoney/QUANTAXIS/task.sh: line 5: python3: command not found
/Users/chenshuai/Documents/Project/easymoney/QUANTAXIS/task.sh: line 5: python3: command not found
/Users/chenshuai/Documents/Project/easymoney/QUANTAXIS/task.sh: line 5: python3: command not found
/Users/chenshuai/Documents/Project/easymoney/QUANTAXIS/task.sh: line 5: python3: command not found
/Users/chenshuai/Documents/Project/easymoney/QUANTAXIS/task.sh: line 5: python3: command not found
/anaconda3/bin/python3: can't open file 'report.py': [Errno 2] No such file or directory
/anaconda3/bin/python3: can't open file 'report.py': [Errno 2] No such file or directory
/anaconda3/bin/python3: can't open file 'report.py': [Errno 2] No such file or directory
/anaconda3/bin/python3: can't open file 'report.py': [Errno 2] No such file or directory
/anaconda3/bin/python3: can't open file 'report.py': [Errno 2] No such file or directory
/anaconda3/bin/python3: can't open file 'report.py': [Errno 2] No such file or directory
/anaconda3/bin/python3: can't open file 'report.py': [Errno 2] No such file or directory
/anaconda3/bin/python3: can't open file 'report.py': [Errno 2] No such file or directory
